### ISSUE TITLE
Cache trivy

### ISSUE THREAD

**Issue by sanselme** [anselmes/cicd#34]
```yaml
- name: Cache Trivy
  uses: actions/cache@v4
  with:
    path: ~/.cache/trivy
    key: ${{ runner.os }}-trivy-${{ github.run_id }}
    restore-keys: |
      ${{ runner.os }}-trivy-
- name: Run Trivy
  uses: aquasecurity/trivy-action@v0.63.0
  with:
    scan-type: fs
    scan-ref: .
    format: sarif
    exit-code: 1
```
